using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class BookStore {
	

	public BookStore(){
		assignedBooks = new List<string>();
	}

	
	public string GetBook(){
		
		if (bookList.Length == assignedBooks.Count || assignedBooks == null) {
			assignedBooks = new List<string>();
		}
		string chosenBook = bookList[(int)(Random.value * bookList.Length)];
		while (assignedBooks.Contains(chosenBook)) {
			chosenBook = bookList[(int)(Random.value * bookList.Length)];
		}
		assignedBooks.Add (chosenBook);
		return chosenBook;
		
	}
	
	List<string> assignedBooks;
	
	//http://www.goodreads.com/list/show/276.Best_Book_Titles + [].forEach.call(document.querySelectorAll("span[itemprop='name']"),function(el){console.log(el.innerHTML);});
	string[] bookList = new string[] {"Do Androids Dream of Electric Sheep?",
		"Philip K. Dick",
		"Pride and Prejudice and Zombies (Pride and Prejudice and Zombies, #1)",
		"Seth Grahame-Smith",
		"Something Wicked This Way Comes (Green Town, #2)",
		"Ray Bradbury",
		"The Hitchhiker's Guide to the Galaxy (Hitchhiker's Guide, #1)",
		"Douglas Adams",
		"I Was Told There'd Be Cake",
		"Sloane Crosley",
		"The Curious Incident of the Dog in the Night-Time",
		"Mark Haddon",
		"The Hollow Chocolate Bunnies of the Apocalypse",
		"Robert Rankin",
		"Eats, Shoots &amp; Leaves: The Zero Tolerance Approach to Punctuation",
		"Lynne Truss",
		"Are You There, Vodka? It's Me, Chelsea",
		"Chelsea Handler",
		"To Kill a Mockingbird",
		"Harper Lee",
		"The Unbearable Lightness of Being",
		"Milan Kundera",
		"Midnight in the Garden of Good and Evil",
		"John Berendt",
		"The Earth, My Butt, and Other Big Round Things",
		"Carolyn Mackler",
		"Butty With a Chance of Meatballs",
		"Judi Barrett",
		"Stop Dressing Your Six-Year-Old Like a Skank: A Slightly Tarnished Southern Belle's Words of Wisdom",
		"Celia Rivenbark",
		"Me Talk Pretty One Day",
		"David Sedaris",
		"The Perks of Being a Wallflower",
		"Stephen Chbosky",
		"The Long Dark Tea-Time of the Soul (Dirk Gently, #2)",
		"Douglas Adams",
		"An Arsonist's Guide To Writers' Homes In New England",
		"Brock Clarke",
		"A Heartbreaking Work of Staggering Genius",
		"Dave Eggers",
		"One Hundred Years of Solitude",
		"Gabriel Garcí­a Márquez",
		"Where the Wild Things Are",
		"Maurice Sendak",
		"Alexander and the Terrible, Horrible, No Good, Very Bad Day",
		"Judith Viorst",
		"Another Bullshit Night in Suck City",
		"Nick Flynn",
		"The Zombie Survival Guide: Complete Protection from the Living Dead",
		"Max Brooks",
		"I am America",
		"Stephen Colbert",
		"How to Lose Friends and Alienate People",
		"Toby Young",
		"John Dies at the End (John Dies at the End, #1)",
		"David Wong",
		"English as a Second Fucking Language: How to Swear Effectively, Explained in Detail With Numerous Examples Taken from Everyday Life",
		"Sterling Johnson",
		"A Clockwork Orange",
		"Anthony Burgess",
		"I Still Miss My Man But My Aim Is Getting Better",
		"Sarah Shankman",
		"A Thousand Splendid Suns",
		"Khaled Hosseini",
		"So Long, and Thanks for All the Fish (Hitchhiker's Guide, #4)",
		"Douglas Adams",
		"The Guernsey Literary and Potato Peel Pie Society",
		"Mary Ann Shaffer",
		"The Devil Wears Prada (The Devil Wears Prada, #1)",
		"Lauren Weisberger",
		"When You Are Engulfed in Flames",
		"David Sedaris",
		"Extremely Loud and Incredibly Close",
		"Jonathan Safran Foer",
		"The Gordonston Ladies Dog Walking Club",
		"Duncan Whitehead",
		"I Have No Mouth and I Must Scream",
		"Harlan Ellison",
		"Tequila Makes Her Clothes Fall Off (Country Music Collection, #1)",
		"Cara North",
		"Neverwhere",
		"Neil Gaiman",
		"The Grapes of Wrath",
		"John Steinbeck",
		"Their Eyes Were Watching God",
		"Zora Neale Hurston",
		"A Confederacy of Dunces",
		"John Kennedy Toole",
		"A Wrinkle in Time (Time, #1)",
		"Madeleine L'Engle",
		"How to Shit in the Woods: An Environmentally Sound Approach to a Lost Art",
		"Kathleen Meyer",
		"When Will Jesus Bring the Pork Chops?",
		"George Carlin",
		"The Man Who Mistook His Wife for a Hat and Other Clinical Tales",
		"Oliver Sacks",
		"Zen And The Art Of Motorcycle Maintenance: An Inquiry Into Values",
		"Robert M. Pirsig",
		"Love in the Time of Cholera",
		"Gabriel Garcí­a Márquez",
		"The Man Who Was Thursday",
		"G.K. Chesterton",
		"For Whom the Bell Tolls",
		"Ernest Hemingway",
		"The Silence of the Lambs  (Hannibal Lecter, #2)",
		"Thomas Harris",
		"Brave New World",
		"Aldous Huxley",
		"Fear and Loathing in Las Vegas",
		"Hunter S. Thompson",
		"Go the Fuck to Sleep",
		"Adam Mansbach",
		"I Hope They Serve Beer in Hell (Tucker Max, #1)",
		"Tucker Max",
		"The Lone Ranger and Tonto Fistfight in Heaven",
		"Sherman Alexie",
		"The Restaurant at the End of the Universe (Hitchhiker's Guide, #2)",
		"Douglas Adams",
		"The Baby Jesus Butt Plug",
		"Carlton Mellick III",
		"All Quiet on the Western Front",
		"Erich Maria Remarque",
		"What to Say When You Talk to Your Self [ Yourself ]",
		"Shad Helmstetter",
		"Don't Pee on My Leg and Tell Me It's Raining: America's Toughest Family Court Judge Speaks Out",
		"Judy Sheindlin",
		"She Got Up Off The Couch: And Other Heroic Acts From Mooreland, Indiana",
		"Haven Kimmel",
		"Well-Behaved Women Seldom Make History",
		"Laurel Thatcher Ulrich",
		"The Electric Kool-Aid Acid Test",
		"Tom Wolfe",
		"Fuck This Book",
		"Bodhi Oser",
		"In God We Trust: All Others Pay Cash",
		"Jean Shepherd",
		"No Country for Old Men",
		"Cormac McCarthy",
		"If On a Winter's Night A Traveler",
		"Italo Calvino",
		"Nostradamus Ate My Hamster",
		"Robert Rankin",
		"The Spy Who Came In from the Cold (George Smiley #3)",
		"John le Carré",
		"Lamb",
		"Christopher Moore",
		"Sense and Sensibility and Sea Monsters",
		"Ben H. Winters",
		"The Sound and the Fury",
		"William Faulkner",
		"Hard-Boiled Wonderland and the End of the World",
		"Haruki Murakami",
		"The Effect of Gamma Rays on Man-in-the-Moon Marigolds",
		"Paul Zindel",
		"The Moon Is a Harsh Mistress",
		"Robert A. Heinlein",
		"Table 21",
		"T. Rafael Cimino",
		"The Particular Sadness of Lemon Cake",
		"Aimee Bender",
		"I Capture the Castle",
		"Dodie Smith",
		"Don't Bend Over in the Garden, Granny, You Know Them Taters Got Eyes",
		"Lewis Grizzard",
		"The Catcher in the Rye",
		"J.D. Salinger",
		"And Then There Were None",
		"Agatha Christie",
		"A Short History of Tractors in Ukrainian",
		"Marina Lewycka",
		"Hitler the Cat Goes West",
		"Robert G. Pielke",
		"This is Not a Novel",
		"David Markson",
		"As I Lay Dying",
		"William Faulkner",
		"On Bullshit",
		"Harry G. Frankfurt",
		"The Lust Lizard of Melancholy Cove",
		"Christopher Moore",
		"The Haunted Vagina",
		"Carlton Mellick III",
		"Of Mice and Men",
		"John Steinbeck",
		"There's a Wocket in My Pocket!",
		"Dr. Seuss",
		"Even God is Single: (So Stop Giving Me a Hard Time).",
		"Karen Salmansohn",
		"Captain Underpants and the Perilous Plot of Professor Poopypants (Captain Underpants, #4)",
		"Dav Pilkey",
		"I Gave You My Heart, but You Sold It Online (Domestic Equalizers Book 3)",
		"Dixie Cash",
		"Half Asleep in Frog Pajamas",
		"Tom Robbins",
		"A Streetcar Named Desire",
		"Tennessee Williams",
		"Practical Demonkeeping",
		"Christopher Moore",
		"How to Talk About Books You Haven't Read",
		"Pierre Bayard"};
}
